language: haskell

branches:
  only:
    - master

sudo: false

addons:
  apt:
    sources:
    - hvr-ghc
    packages:
    - ghc-7.10.2
    - libgmp-dev

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=~/.local/bin:$PATH
  - travis_retry curl -L https://github.com/commercialhaskell/stack/releases/download/v0.1.4.0/stack-0.1.4.0-x86_64-linux.tar.gz | tar xz -C ~/.local/bin
  - export PATH=/opt/ghc/7.10.2/bin:$PATH
  - chmod a+x ~/.local/bin/stack

install:
  - stack +RTS -N2 -RTS setup
  - stack +RTS -N2 -RTS build --only-snapshot

script:
  - stack +RTS -N2 -RTS build --test --haddock

cache:
  directories:
  - $HOME/.stack
